name: Update Formula in Tap
# This workflow will automatically update our product formulae on the release of
# new versions
on:
  repository_dispatch:
    types: [version-updated]

jobs:
  update-formula:
    name: Update Formula
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Generate new formula
        run: |
          python generate.py ${{github.event.client_payload.version}}
      - 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump zine to ${{github.event.client_payload.version}}
          file_pattern: Formula/*.rb
          commit_user_name: Github Actions
          commit_user_email: github-actions-bot@users.noreply.github.com